---

- hosts: webservers

  tasks:
    - name: Check if host is alive
      ansible.builtin.ping: ~
    - name: Execute a simple command
      ansible.builtin.shell: echo "Ansible was here !" > ansible.txt

- hosts: dbservers

  tasks: 
  - name: Get stat of a file
    ansible.builtin.stat:
      path: /etc/hosts