- name: restart_nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
- name: restart_mariadb
  ansible.builtin.service:
    name: nginx
    state: restarted
- name: restart_php-fpm
  ansible.builtin.service:
    name: php8.2-fpm
    state: restarted