name: lpdevops

services:

    ##########
    # System #
    ##########

    system:
        hostname: lpdevops
        build:
            context: ..
            dockerfile: docker/Dockerfile
        image: lpdevops:20230221141601
        volumes:
            - ../..:${DIR}
        environment:
            DIR: ${DIR}
            CACHE_DIR: ${CACHE_DIR}
        working_dir: ${DIR}
        # Use default docker bridge network
        network_mode: bridge
