name: lpdevops

services:

    ##########
    # System #
    ##########

    system:
        hostname: lpdevops
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: system
        image: lpdevops:20230129001716
        volumes:
            - ../..:${DIR}
        tmpfs:
          - /tmp
        environment:
            DIR: ${DIR}
            CACHE_DIR: ${CACHE_DIR}
        working_dir: ${DIR}
        # Use default docker bridge network
        network_mode: bridge
