name: devops

services:

    ##########
    # System #
    ##########

    system:
        hostname: devops
        build:
            context: ..
            dockerfile: docker/Dockerfile
        image: devops:20250119183450
        pull_policy: never
        volumes:
            - ../..:${MANALA_DIR}
        environment:
            MANALA_DIR: ${MANALA_DIR}
            MANALA_CACHE_DIR: ${MANALA_CACHE_DIR}
        working_dir: ${MANALA_DIR}
        networks:
          - network

networks:
  network:
    name: devops
