all:
  hosts:
    ansible-vm-01:
      ansible_host: 192.168.251.129
      ansible_user: ansible
      ansible_python_interpreter: /usr/bin/python3.11
    ansible-vm-02:
      ansible_host: 192.168.251.130
      ansible_user: ansible
      ansible_python_interpreter: /usr/bin/python3.11
      
  children:
    webservers:
      hosts:
        ansible-vm-01: ~
        ansible-vm-02: ~
    production:
      hosts:
        ansible-vm-01: ~
    staging:
      hosts:
        ansible-vm-02: ~
    dbservers:
      hosts:
        ansible-vm-01: ~
